### PR TITLE
true uniform function

### PR DESCRIPTION
**Pull request by timCF**
Here I tried to fix scaling bug ( on uniform function ) what was reported some time ago. Please check it and merge if it works!

Regards, timCF.

### CODE REVIEW

**Comment by jj1bdx** [comment]
Your code has been merged to `next` branch. I need to review the code first.

**Comment by jj1bdx** [comment]
Code tagged as https://github.com/jj1bdx/sfmt-erlang/tree/TimCF-pr24

**Comment by timCF** [comment]
Hi! My local dieharder tests are perfect ( generated and tested 500000000 integers ). All dieharder tests passed. If you review these fixes in the near future - you will help me very much!

**Comment by jj1bdx** [comment]
Code for `uniform_s/2` is still required, and I need to write a test case for the new algorithm.

**Pull request merged**
