### PR TITLE
r3: support rebar3

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by jj1bdx** [comment]
@fenollp Thx for the patch! I'll check the rebar3 patch before merging it. Give me a little time.

**Comment by jj1bdx** [comment]
@fenollp Merged to `master` branch after tested this patch set on `next` branch. Thx for the patch again!

**Comment by fenollp** [comment]
Thanks :) When can we expect a new release so that hex.pm shows this lib as usable by rebar3?

**Comment by jj1bdx** [comment]
@fenollp Allow me a few weeks - I need to do the Code BEAM STO stuff first right now :) After coming back from Sweden to Japan I will take a look at making a new release.

**Comment by fenollp** [comment]
Sure, there’s no rush. Though it should only be a matter of `rebar3 hex cut` :)

**Comment by jj1bdx** [comment]
@fenollp Could you tell me what I should do so that this lib is recognized as usable by rebar3? Any pointer appreciated.

**Comment by jj1bdx** [comment]
@fenollp A question: sfmt-erlang has already been published as `sfmt` in hex.pm. Any idea to tell a new release of sfmt-erlang supports rebar3 at hex.pm?

**Comment by fenollp** [comment]
I have never been through the same path but I believe that `rebar3 hex publish` will show you that before confirming. What does it show you?

**Comment by jj1bdx** [comment]
@fenollp I'll check it later > `rebar3 hex publish`

**Pull request merged**
